class AppStrings {
  AppStrings._();

  // Navegación y General
  static const appName = 'PWMS';
  static const appTitle = 'PWMS: Sistema de Gestión del Mundo Platinum';
  static const searchHint = 'Buscar especies, instancias o ubicaciones...';
  static const rootLocationName = 'Mundo';
  static const cancel = 'Cancelar';
  static const save = 'Guardar';
  static const delete = 'Eliminar';
  static const edit = 'Editar';
  static const move = 'Trasladar';
  static const link = 'Relacionar';
  static const attachFile = 'Adjuntar archivo';
  static const confirm = 'Confirmar';
  static const close = 'Cerrar';
  static const add = 'Agregar';
  static const addShort = 'Añadir';
  static const change = 'Cambiar';
  static const viewAll = 'Ver todo';
  static const apply = 'Aplicar';
  static const all = 'Todos';
  static const selectOptionPrompt = 'Seleccionar opción.';
  static const selectMagnitudePrompt = 'Seleccionar magnitud.';
  static const errorPrefix = 'Error: ';
  static const errorGeneric = 'Ha ocurrido un error inesperado.';

  // Pestañas y Navegación Principal
  static const tabHome = 'Inicio';
  static const tabEntities = 'Instancias';
  static const tabLocations = 'Ubicaciones';
  static const tabCatalog = 'Catálogo';
  static const tabHistory = 'Historial';
  static const tabSearch = 'Buscar';

  // Pantalla de Inicio
  static const recentEntitiesTitle = 'Instancias recientes';
  static const activityTitle = 'Historial de actividad';
  static const universeCatalogTitle = 'Catálogo de especies';
  static const locationsTitle = 'Grafo de ubicaciones';
  static const noRecentObjects = 'Sin objetos recientes.';
  static const mainLocations = 'Ubicaciones principales';
  static const objectsCountSuffix = 'objetos';
  static const latestCatalogSpecies = 'Últimas especies en el catálogo';
  static const viewCatalog = 'Ver catálogo';
  static const noRecentActivity = 'Sin actividad reciente.';
  static const topLocationsTitle = 'Ubicaciones principales';
  static const objectsLabel = 'objetos';
  static const viewCatalogAction = 'Ver catálogo';
  static const viewAllAction = 'Ver todo';

  // Tipos y Plantillas de Entidades
  static const typeObject = 'Objeto';
  static const typeLivingBeing = 'Ser vivo';
  static const typeDocument = 'Documento';
  static const typeProject = 'Proyecto';
  static const typeMemory = 'Recuerdo';

  // Formularios y Terminología de Registro
  static const registerObjectTitle = 'Registrar en el mundo';
  static const editInstanceTitle = 'Editar instancia';
  static const nameLabel = 'Nombre de la especie';
  static const typeLabel = 'Tipo de especie';
  static const locationLabel = 'Ubicación';
  static const quantityLabel = 'Magnitud';
  static const unitLabel = 'Unidad';
  static const barcodeLabel = 'Código de barras';
  static const notesLabel = 'Notas de instancia';
  static const descriptionLabel = 'Descripción técnica';
  static const brandLabel = 'Marca';
  static const isUniqueLabel = 'Especie única';
  static const monetaryValueLabel = 'Valor monetario';
  static const currencyLabel = 'Moneda';
  static const isSaleLabel = '¿Registrar como venta?';
  static const takePhoto = 'Tomar fotografía';
  static const chooseGallery = 'Elegir de la galería';
  static const photoLabel = 'Fotografía principal';
  static const chooseFromCatalog = 'Elegir del catálogo';
  static const showMoreFields = 'Campos adicionales';
  static const showFewerFields = 'Ocultar campos adicionales';
  static const registerAction = 'Registrar en el mundo';
  static const saveChangesAction = 'Guardar cambios';
  static const changePhotoAction = 'Cambiar fotografía';
  static const selectFromCatalogChoice = 'Elegir del catálogo';
  static const createNewSpeciesChoice = 'Crear nueva especie';
  static const instantiateTab = 'Instanciar';
  static const createSpeciesTab = 'Crear especie';
  static const addSubspeciesTab = 'Crear subespecie';
  static const autoFillTab = 'Autollenado';
  static const addSubspeciesChoice = 'Agregar subespecie';

  // Catálogo de Especies
  static const catalogTitle = 'Catálogo de especies';
  static const newSpeciesTitle = 'Nueva especie';
  static const createSpeciesHeader = 'Crear especie en catálogo';
  static const saveSpeciesAction = 'Guardar especie';
  static const instantiateAction = 'Instanciar';
  static const emptyCatalog = 'El catálogo está vacío.';
  static const singleInstanceError = 'Esta especie es única y ya existe en tu mundo.';
  static const singleInstanceSubspeciesError = 'La subespecie de esta especie única ya está instanciada en el mundo.';
  static const duplicateSpeciesNameError = 'Ya existe una especie con este nombre.';
  static const duplicatePhotoError = 'Ya existe una especie con esta misma imagen.';
  static const duplicateAttachmentError = 'Este archivo adjunto ya existe en la especie.';
  static const latestCatalogSpeciesTitle = 'Últimas especies en el catálogo';

  // Subespecies y Variantes
  static const subspeciesTitle = 'Subespecies';
  static const subspeciesCountTitle = 'Subespecies';
  static const addSubspecies = 'Añadir subespecie';
  static const addBrand = 'Agregar subespecie';
  static const noSubspecies = 'Sin subespecies registradas.';
  static const noSubspeciesDefined = 'No hay subespecies.';
  static const subspeciesNameLabel = 'Nombre de subespecie';
  static const editSubspecies = 'Editar subespecie';
  static const deleteSubspecies = 'Eliminar subespecie';
  static const defaultSubspeciesName = 'Genérica';
  static const viewCatalogSpecies = 'Ver especie en catálogo';
  static const viewSpeciesDetail = 'Ver detalle de especie';
  static const masterCatalogSpeciesBadge = 'ESPECIE DE CATÁLOGO MAESTRO';
  static const registeredPropertiesAndMagnitudes = 'Propiedades y magnitudes registradas';
  static const notInstantiatedYet = 'Esta especie aún no ha sido instanciada en tu mundo.';
  static const registeredInstance = 'Instancia registrada';
  static const speciesInstantiatedSuccess = 'Especie instanciada con éxito.';
  static const selectSpeciesToInstantiate = 'Selecciona una especie para instanciar.';
  static const instantiateCatalogSpeciesHeader = 'Instanciar especie de catálogo';
  static const catalogSpeciesLabel = 'Especie de catálogo:';
  static const selectSpeciesPrompt = 'Selecciona una especie...';
  static const physicalLocation = 'Ubicación física';
  static const savedInContainer = 'Guardado en contenedor';
  static const selectContainerPrompt = 'Selecciona contenedor (relación GUARDADO_EN):';
  static const noContainerObjectsAvailable = 'No hay objetos contenedores disponibles.';
  static const selectContainerObject = 'Selecciona objeto contenedor';
  static const containerObjectLabel = 'Objeto contenedor';
  static const magnitudesAndSpecificProps = 'Magnitudes y propiedades específicas:';
  static const subspeciesOrBrandCommercialLabel = 'Subespecie';
  static const selectSubspeciesOrBrandPrompt = 'Selecciona subespecie';
  static const quantityToInstantiateLabel = 'Cantidad';
  static const addPropertyOrUnitTitle = 'Agregar propiedad o unidad';
  static const propertyNameHint = 'Nombre de la propiedad (ej. Masa, Volumen, Longitud)';
  static const selectUnitPrompt = 'Seleccionar unidad de medida';
  static const editSubspeciesDraftTitle = 'Editar subespecie (borrador)';
  static const newSubspeciesVariantTitle = 'Nueva subespecie (variante)';
  static const subspeciesPhotoLabel = 'Fotografía de la subespecie';
  static const nameOrVariantLabel = 'Nombre';
  static const nameOrVariantHint = 'Ej. Alcalina de alto rendimiento';
  static const brandHint = 'Ej. Duracell';
  static const barcodeHint = 'Ej. 750123456789';
  static const notesSpecialEditionHint = 'Ej. Edición especial';
  static const editSpeciesTitle = 'Editar especie';
  static const createSpeciesTitle = 'Crear nueva especie';
  static const noTemplate = 'Sin plantilla';
  static const selectBaseSpeciesPrompt = 'Seleccionar especie base';
  static const useSpeciesAsBaseTemplate = 'Usar especie como plantilla base';
  static const selectBaseTemplateHint = 'Seleccionar plantilla base...';
  static const nameIsImmutable = 'El nombre es inmutable.';
  static const unitsAndMagnitudesTitle = 'Unidades de medida';
  static const addUnitAction = 'Agregar medida';
  static const noAdditionalUnitsAdded = 'Sin unidades adicionales agregadas.';
  static const removeUnitAction = 'Eliminar unidad de medida';
  static const subspeciesOrBrands = 'Subespecies';
  static const addBrandAction = 'Agregar subespecie';
  static const noSubspeciesOrBrandsAdded = 'Sin subespecies agregadas.';
  static const noBarcode = 'Sin código de barras';
  static const chooseFromCatalogAction = 'Elegir del catálogo';
  static const createNewSpeciesAction = 'Crear nueva especie';
  static const createFirstSpeciesAction = 'Crear primera especie';
  static const cannotDeleteOnlySubspecies = 'No se puede eliminar la única subespecie de una especie.';
  static const cannotDeleteOnlySubspeciesTooltip = 'No se puede eliminar la única subespecie.';
  static const subspeciesLabel = 'Subespecie:';

  // Ubicaciones y Grafo Jerárquico
  static const locationsGraphTitle = 'Ubicaciones';
  static const newLocationTitle = 'Nueva ubicación';
  static const newSubLocationTitle = 'Nueva ubicación hija';
  static const childLocationsTitle = 'Ubicaciones hijas';
  static const createNodeHeader = 'Crear ubicación';
  static const locationNameLabel = 'Nombre de ubicación';
  static const locationDescriptionLabel = 'Descripción de ubicación';
  static const createObjectHere = 'Instanciar aquí';
  static const storedObjectsTitle = 'Instancias almacenadas aquí';
  static const emptyLocation = 'Ubicación vacía.';
  static const selectLocationPrompt = 'Seleccionar ubicación';
  static const locationHasNoObjectsOrSublocations = 'Esta ubicación no contiene objetos ni sububicaciones.';
  static const containerLabel = 'Contenedor';
  static const cannotMoveLocationSelfError = 'No se puede mover una ubicación dentro de sí misma ni de sus ubicaciones hijas.';
  static const circularLocationError = 'No se puede mover una ubicación dentro de sí misma ni de sus ubicaciones hijas.';
  static const instantiateObjectHere = 'Instanciar objeto aquí';
  static const treeView = 'Vista de árbol';
  static const graphView = 'Vista de grafo';
  static const previousLocation = 'Ubicación previa';
  static const newGraphLocation = 'Nueva ubicación en el grafo';
  static const movedSuccessfullyGraph = 'trasladado exitosamente en el grafo.';
  static const moveErrorPrefix = 'Error al mover: ';
  static const moveInGraph = 'Trasladar en el grafo';
  static const selectNewLocationOrContainer = 'Selecciona la nueva ubicación o contenedor:';
  static const createLocationOnTheFly = 'Crear nueva ubicación sobre la marcha';
  static const locationNameHint = 'Ej. Estantería 3 o Garaje';
  static const confirmMoveAction = 'Confirmar traslado';
  static const locationGraphNode = 'Ubicación en el grafo';

  // Detalle, Archivos y Confirmaciones
  static const masterDescription = 'Descripción maestra';
  static const attachmentsTitle = 'Archivos y documentos adjuntos';
  static const emptyAttachments = 'Sin archivos adjuntos.';
  static const deleteConfirmationTitle = 'Eliminar elemento';
  static const deleteConfirmationMessage = '¿Deseas eliminar este elemento de tu mundo?';
  static const zeroQuantityMessage = 'La magnitud llegó a cero. ¿Deseas eliminar la instancia?';
  static const mustProvideEntityOrGroup = 'Debe proporcionarse entidad o grupo.';
  static const photoNotAvailable = 'Fotografía no disponible.';
  static const instanceUpdatedSuccess = 'Instancia actualizada con éxito.';
  static const updateErrorPrefix = 'Error al actualizar: ';
  static const instantiatedObject = 'Objeto instanciado';
  static const graphLocationOrContainer = 'Ubicación en el grafo (lugar o contenedor)';
  static const instanceNotesLabel = 'Notas';
  static const specificDetailsHint = 'Detalles específicos...';

  // Unidades y Categorías de Medida
  static const unitCategoryPhysical = 'Magnitudes físicas y métricas';
  static const unitCategoryDigital = 'Digital y almacenamiento';
  static const unitCategoryFinancial = 'Financiero y monetario';
  static const unitCategoryTime = 'Tiempo y duración';
  static const unitCategoryAbstract = 'General y conteo';
  static const unitUnits = 'unidades';
  static const unitUnitSingle = 'unidad';
  static const unitPieces = 'piezas';
  static const unitKg = 'kg';
  static const unitGrams = 'g';
  static const unitLiters = 'L';
  static const unitMeters = 'm';
  static const unitsLabel = 'unidades';

  // Servicio de Almacenamiento Local
  static const fileNotFoundInStorage = 'Archivo no encontrado en el almacenamiento local.';
  static const fileDeleteFailure = 'Error al eliminar el archivo local.';

  // Requisitos y Dependencias (NECESITA)
  static const requirementsTitle = 'Relaciones de necesidad';
  static const addRequirement = 'Añadir requisito';
  static const addRequirementTitle = 'Agregar requisito NECESITA';
  static const noRequirements = 'Sin requisitos registrados.';
  static const noRequirementsDefined = 'No hay necesidades definidas.';
  static const noCatalogSpeciesForRequirement = 'No hay especies en el catálogo para requerir.';
  static const selectRequiredSpeciesPrompt = 'Selecciona la especie requerida e indica la cantidad necesaria:';
  static const requiredSpeciesLabel = 'Especie requerida';
  static const requirementTypeLabel = 'Tipo de requisito';
  static const requirementTargetLabel = 'Especie o elemento requerido';
  static const quantityRequiredLabel = 'Cantidad requerida';
  static const quantityRequiredHint = 'Ej. 6';
  static const requirementNotesLabel = 'Notas del requisito';
  static const notesOptionalLabel = 'Notas (opcional)';
  static const notesRequirementHint = 'Ej. Baterías para encendido';
  static const needsPrefix = 'NECESITA';

  // Atributos y Plantillas Personalizadas
  static const customAttributesTitle = 'Atributos personalizados';
  static const noCustomAttributesDefined = 'Sin atributos personalizados definidos.';
  static const addAttributeTitle = 'Agregar atributo';
  static const attributeNameHint = 'Ej. Voltaje, Garantía, Color...';
  static const attributeValueHint = 'Ej. 220V, 2 años, Rojo...';
  static const templateCustomCreate = 'Crear plantilla personalizada';
  static const templateNameLabel = 'Nombre de la plantilla';
  static const templateExamplesHint = 'Ej. Herramienta eléctrica, Dispositivo...';
  static const templateUnitsHintLabel = 'Unidades de medida habituales (separadas por coma)';
  static const templateUnitsExamples = 'Ej. piezas, kg, metros';
  static const saveTemplateAction = 'Guardar plantilla';
  static const customAttributeEditorTitle = 'Editor de atributo personalizado';
  static const attributeNameLabel = 'Nombre del atributo';
  static const attributeTypeLabel = 'Tipo de dato';
  static const attributeValueLabel = 'Valor';
  static const templateSavedSuccess = 'Plantilla guardada con éxito.';

  // Entidades, Demografía y Grupos
  static const noEntitiesRegistered = 'No hay objetos registrados.';
  static const instanceWorldHeader = 'INSTANCIA DEL MUNDO';
  static const addInstanceNotesHint = 'Añadir notas sobre esta instancia...';
  static const majorityDemographics = 'Demografía mayoritaria';
  static const standardSpeciesProfile = 'Perfil estándar de la especie (sin notas diferenciales)';
  static const dynamicPopulationManagement = 'Gestión dinámica de población';
  static const populationManagementInstruction = 'El toque corto en los botones de ajuste resta o suma una unidad. El toque prolongado activa la rueda de selección. El toque en la cifra permite ingresar la población objetivo directamente.';
  static const populationLabel = 'Población';
  static const groupInstanceDetail = 'Detalle de instancias en el grupo';
  static const noInstancesAvailableToDelete = 'No hay instancias disponibles para eliminar.';
  static const addByWheelTitle = 'Añadir por rueda de selección';
  static const removeByWheelTitle = 'Eliminar por rueda de selección';
  static const directPopulationAdjustmentTitle = 'Ajuste directo de población';
  static const currentPopulationLabel = 'Población actual';
  static const newTargetPopulationLabel = 'Nueva población objetivo';
  static const applyCalculationAction = 'Aplicar cálculo';
  static const noChangesLabel = 'Sin cambios';
  static const noInstancesToDelete = 'No hay instancias disponibles para eliminar.';
  static const addByWheel = 'Añadir por rueda de selección';
  static const removeByWheel = 'Eliminar por rueda de selección';
  static const noChanges = 'Sin cambios';
  static const directPopulationAdjustment = 'Ajuste directo de población';
  static const currentPopulation = 'Población actual:';
  static const newTargetPopulation = 'Nueva población objetivo';
  static const targetPopulationHint = 'Ej. 15';
  static const applyCalculation = 'Aplicar cálculo';

  // Relaciones y Grafo Semántico
  static const selectTargetEntityError = 'Selecciona una entidad objetivo.';
  static const selectDirectedRelationTypePrompt = 'Seleccionar tipo de relación dirigida';
  static const directedRelationTypeLabel = 'Tipo de relación dirigida de origen a destino';
  static const searchTargetEntityLabel = 'Buscar entidad destino';
  static const noEntitiesAvailableToRelate = 'No hay entidades disponibles para relacionar.';
  static const createDirectedRelationAction = 'Crear relación dirigida';
  static const circularRelationError = 'No se puede crear un vínculo circular: el elemento ya forma parte o contiene la entidad destino.';
  static const selectElementToRelate = 'Selecciona el elemento a relacionar';
  static const directedRelationCreatedSuccess = 'Relación dirigida creada con éxito.';
  static const saveRelationErrorPrefix = 'Error al guardar relación: ';
  static const sourceObjectLabel = 'Objeto origen';
  static const directedRelationInWorld = 'Relación dirigida en tu mundo';
  static const semanticRelationType = 'Tipo de vínculo semántico';
  static const targetOfRelation = 'Destino del vínculo:';
  static const noOtherRelationCandidates = 'No hay otros elementos disponibles para relacionar.';
  static const selectTargetElement = 'Selecciona elemento destino';
  static const targetObjectLabel = 'Objeto destino';
  static const establishDirectedRelation = 'Establecer vínculo dirigido';
  static const selectTargetEntity = 'Selecciona una entidad objetivo.';
  static const selectDirectedRelationType = 'Seleccionar tipo de relación dirigida';
  static const searchTargetEntity = 'Buscar entidad destino';
  static const targetInstanceLabel = 'Instancia destino';
  static const createDirectedRelation = 'Crear relación dirigida';
  static const interactiveRelationGraph = 'Grafo interactivo de relaciones';
  static const interactiveRelationsGraphTitle = 'Grafo interactivo de relaciones';
  static const noDirectedRelations = 'Sin relaciones dirigidas registradas.';
  static const noDirectedRelationsRegistered = 'Sin relaciones dirigidas registradas.';
  static const currentInstance = 'Instancia actual';
  static const currentInstanceLabel = 'Instancia actual';
  static const externalEntity = 'Entidad externa';
  static const sourceEntity = 'Entidad origen';
  static const sourceEntityLabel = 'Entidad origen';
  static const targetEntity = 'Entidad destino';
  static const targetEntityLabel = 'Entidad destino';
  static const deleteRelation = 'Eliminar relación';
  static const deleteRelationTooltip = 'Eliminar relación';
  static const loadRelationsErrorPrefix = 'Error al cargar relaciones: ';
  static const relationsLoadErrorPrefix = 'Error al cargar relaciones: ';
  static const centralInstancePrefix = 'Instancia central: ';
  static const centralInstanceLabel = 'Instancia central';

  // Historial de Actividad
  static const logRegistered = 'Registrado en tu mundo:';
  static const logEdited = 'Editado';
  static const logEditedInfo = 'Editada información de';
  static const logDeleted = 'Eliminado de tu mundo:';
  static const logMoved = 'Trasladado';
  static const logFrom = 'de';
  static const logTo = 'a';
  static const logFileAttached = 'Adjuntado archivo';
  static const logFileDeleted = 'Eliminado archivo';
  static const logRelationEstablished = 'Vínculo establecido:';
  static const logRelationDeleted = 'Vínculo eliminado:';
  static const logPhotoUpdated = 'Actualizada fotografía principal de';
  static const logPhotoDeleted = 'Eliminada fotografía principal de';
  static const logQuantityAdjusted = 'Cantidad ajustada de';
  static const noActivityRegistered = 'Sin actividad registrada.';

  // Pantalla de Búsqueda
  static const objectsCategory = 'Objetos';
  static const historyCategory = 'Historial';
  static const noHistoryResults = 'Sin resultados de historial.';

  // Notificaciones y Recordatorios
  static const notificationsAndRemindersTitle = 'Notificaciones y recordatorios';
  static const refreshAction = 'Actualizar';
  static const noPendingNotifications = 'No tienes notificaciones pendientes.';
  static const allElementsUpToDate = 'Todos tus elementos están al día y requerimientos cubiertos.';
  static const loadNotificationsErrorPrefix = 'Error al cargar notificaciones: ';
  static const snoozeReminderTitle = 'Posponer recordatorio';
  static const snoozeReminderPrompt = 'Elige por cuánto tiempo deseas ocultar este aviso:';
  static const snoozeOneDay = 'Posponer 1 día';
  static const snoozeThreeDays = 'Posponer 3 días';
  static const snoozeOneWeek = 'Posponer 1 semana';
  static const snoozeAction = 'Posponer';
  static const dismissAction = 'Descartar';

  // Gestión de Población y Caducidad
  static const heterogeneousGroupQuantityError = 'No se puede modificar la cantidad en grupos heterogéneos.';
  static const heterogeneousGroupQuickAdjustmentError = 'No se pueden realizar ajustes rápidos en grupos heterogéneos.';
  static const expirationDateForNewInstancePrompt = 'Fecha de caducidad para la nueva instancia';
  static const expirationDateForNewInstancesPrompt = 'Fecha de caducidad para las nuevas instancias';
  static const adjustQuantityTitle = 'Ajustar cantidad';
  static const newTotalQuantityLabel = 'Nueva cantidad total';
  static const deleteGroupTitle = 'Eliminar grupo';
  static const confirmDeleteGroupMessage = '¿Estás seguro de que deseas reducir la cantidad a cero y eliminar todas las instancias de este grupo?';
  static const instancesDeletedSuccess = 'Instancias eliminadas con éxito.';
  static const selectExpirationDateForNewInstancesPrompt = 'Selecciona la fecha de caducidad de las nuevas instancias.';
  static const populationUpdatedSuccessPrefix = 'Población actualizada correctamente a ';
  static const adjustPopulationErrorPrefix = 'Error al ajustar la población: ';
  static const adjustmentNotAvailableTitle = 'Ajuste no disponible';
  static const heterogeneousGroupAdjustmentMessage = 'No es posible ajustar la población directamente en grupos heterogéneos. Abre la vista dedicada de grupo para gestionar cada instancia individualmente.';
  static const understoodAction = 'Entendido';
  static const adjustPopulationTitle = 'Ajustar población';
  static const homogeneousGroupHeaderPrefix = 'Grupo homogéneo (';
  static const homogeneousGroupHeaderSuffix = ' actuales)';
  static const variedSubspeciesLabel = 'Subespecies variadas';
  static const statusExpired = 'Caducado';
  static const statusWarning = 'Próximo a vencer';
  static const generalSpeciesPrefix = 'Especie general: ';
  static const expirationDateOptionalLabel = 'Fecha de caducidad (opcional)';
  static const noExpirationDate = 'Sin fecha de caducidad';
  static const removeExpirationDateTooltip = 'Quitar fecha de caducidad';
  static const noInstancesAvailableInGroup = 'No hay instancias disponibles en este grupo.';
  static const totalPopulationPrefix = 'Población total: ';
  static const homogeneousGroupProperties = 'Grupo homogéneo (propiedades idénticas)';
  static const deleteInstanceTitle = 'Eliminar instancia';
  static const deleteInstanceConfirmationMessage = '¿Estás seguro de que deseas eliminar esta instancia de tu mundo?';
}
